baseURL = 'https://cab-docs.cynteocloud.com/'
languageCode = 'en-us'
title = 'Cynteo Alert Bridge Documentation'

[params]
  description = 'Connect Azure Monitor alerts to your ITSM automatically'
  author = 'Cynteo Cloud'
  repo = 'https://github.com/cynteocloud/cab-public-docs'
  
[menu]
  [[menu.main]]
    name = 'Home'
    url = '/'
    weight = 1
  
  [[menu.main]]
    name = 'Getting Started'
    url = '/getting-started/'
    weight = 2
    
  [[menu.main]]
    name = 'Platforms'
    url = '/platforms/'
    weight = 3
    
  [[menu.main]]
    name = 'Guides'
    url = '/guides/'
    weight = 4
    
  [[menu.main]]
    name = 'Reference'
    url = '/reference/'
    weight = 5
    
  [[menu.main]]
    name = 'Troubleshooting'
    url = '/troubleshooting/'
    weight = 6

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokai'
    lineNos = false
    
[outputs]
  home = ['HTML', 'RSS', 'JSON']

